### PR TITLE
Czech initial support

### PR DESCRIPTION
**Pull request by Tony763**
Prepared in colaboration with @Manasovo

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey Tony, thanks for the help in bringing Mycroft to more langauges. I wanted to make sure you were aware of translate.mycroft.ai which is the platform we use to manage all the translation efforts. 

It's just not viable for us to manage manual language updates to repo's like this given the number of languages and Skills. So I'll try to take a look at all these PR's but it will take some time. If we can get the translations into translate.mycroft.ai we can get them all merged in the next run for all languages. It also means they won't get over written if there is an alternative translation listed in the system.

**Comment by Tony763** [comment]
Hi, I know about a translate portal but for me is this much faster and cleaner way especially when intents are write in adapt. Direct translation then just mean nothing. All these PR are easy one, next batch of translations I had prepared need also changes inside code as some things are hardcoded in English. I already prepared them but as we talked in [homeassistant skill](https://github.com/MycroftAI/mycroft-homeassistant/pull/38#issuecomment-675196351), I need to rewrite them from json file to match_voc.

**Comment by krisgesling** [comment]
Hey Tony,

We're a small team and we have to be very careful about where we spend our time which is one of the key reasons we setup the translation platform. There's just no way that we can review the number of PR's it would require to keep language translations up to date by doing them all through Github. 

I know there are limitations to the translate platform but we need to address those, rather than going back to manual processing of translations. 

The translate platform is also more accessible for more people, as many of our translation contributors aren't developers.

I really don't know when I'll get time to look at all these and I'd again encourage you to add them to translate.mycroft.ai instead.

**Comment by Manasovo** [comment]
Hey Kris,

I fully understand your position on maintaining the maximum quality of translations and code. But Tony is right ! Because 1:1 translation from english is useless and unusable for czech. Czech language requires wider access and we had to update lot of  code  which are hardcoded  in english and adapt all voc, dialog and intent files.

Just imagine :-) Take our code as the first initialization for czech language and then merge with existing data from translate.mycroft.ai ? Or update data from our code to translate.mycroft.ai. 

I guarantee that our code is carefully written and tested on every skill for a long time :-)

Have a clear mind and make a right decision :-)


Marek

**Pull request merged**
