### PR TITLE
if user requests default switch to precise

### PR DESCRIPTION
**Pull request by krisgesling**
If a user asked to "set the listener to default" the Skill would switch to Pocketsphinx.

Precise is the default for all new installs and vast majority of users.

## To test
"Hey Mycroft, set the listener to default"

### CODE REVIEW

**Comment by krisgesling** [comment]
@forslund These tests are failing in an interesting way on my machine so I pushed them for you to take a look at.

It seems like the system doesn't finish setting the listener from the previous request before the next test starts as the retry always succeeds.

**Comment by forslund** [comment]
Can you provide the output for the file? I can't seem to reproduce what you're describing...

**Comment by krisgesling** [comment]
Well that's interesting. This is what I get:
```
2020-04-23 09:32:36.903 | INFO     | 37440 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2020-04-23 09:32:40.387 | INFO     | 37440 | msm.mycroft_skills_manager | Best match (1.0): mycroft-configuration by mycroftai
2020-04-23 09:32:41.534 | INFO     | 37440 | msm.skill_entry | Nothing new for mycroft-configuration
2020-04-23 09:32:41.547 | INFO     | 37440 | msm.mycroft_skills_manager | Best match (1.0): mycroft-configuration by mycroftai
-------- TEST SETUP --------
extra_skills: []
platform: mycroft_mark_1
test_skills:
- mycroft-configuration

----------------------------
Starting all mycroft-core services
Initializing...
Starting background service bus
CAUTION: The Mycroft bus is an open websocket with no built-in security
         measures.  You are responsible for protecting the local port
         8181 with a firewall as appropriate.
Starting background service skills
Starting background service audio
Starting background service voice
Starting background service enclosure
Running behave with the arguments ""
2020-04-23 09:32:42.640 | INFO     | 37674 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2020-04-23 09:32:46.172 | INFO     | 37674 | mycroft.messagebus.client.client:on_open:67 | Connected
2020-04-23 09:32:48.926 | INFO     | 37674 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2020-04-23 09:32:52,887 | Voight Kampff | INFO | Waiting for messagebus connection...
2020-04-23 09:32:52,887 | Voight Kampff | INFO | Waiting for skills to be loaded...
2020-04-23 09:33:01,503 | Voight Kampff | INFO | Starting tests for Change the active wake word listening engine
Feature: Change the active wake word listening engine # features/change-listener.feature:1

  Scenario Outline: User asks to change the listener -- @1.1 set the listener requests      # features/change-listener.feature:10
    Given an english speaking user                                                          # features/steps/utterance_responses.py:120 0.001s
    When the user says "set the listener to pocketsphinx"                                   # features/steps/utterance_responses.py:125 0.000s
    Then "mycroft-configuration" should reply with "I've set the listener to pocket sphinx" # features/steps/utterance_responses.py:149
    Then "mycroft-configuration" should reply with "I've set the listener to pocket sphinx" # features/steps/utterance_responses.py:149 0.714s

  Scenario Outline: User asks to change the listener -- @1.2 set the listener requests  # features/change-listener.feature:11
    Given an english speaking user                                                      # features/steps/utterance_responses.py:120 0.000s
    When the user says "set the listener to precise"                                    # features/steps/utterance_responses.py:125 0.001s
    Then "mycroft-configuration" should reply with "I've set the listener to precise"   # features/steps/utterance_responses.py:149
    Then "mycroft-configuration" should reply with "I've set the listener to precise"   # features/steps/utterance_responses.py:149 10.019s
      Assertion Failed: Mycroft responded with:
      Mycroft: listener.same.dialog(ConfigurationSkill)
      "The listener is already set to precise."
      
      Captured stdout:
      Matching with the dialog file: set.listener.dialog
      
      Captured logging:
      INFO:msm.mycroft_skills_manager:Best match (1.0): mycroft-configuration by mycroftai

AUTO-RETRY SCENARIO (attempt 1)

  Scenario Outline: User asks to change the listener -- @1.2 set the listener requests  # features/change-listener.feature:11
    Given an english speaking user                                                      # features/steps/utterance_responses.py:120 0.000s
    When the user says "set the listener to precise"                                    # features/steps/utterance_responses.py:125 0.000s
    Then "mycroft-configuration" should reply with "I've set the listener to precise"   # features/steps/utterance_responses.py:149
    Then "mycroft-configuration" should reply with "I've set the listener to precise"   # features/steps/utterance_responses.py:149 0.455s
AUTO-RETRY SCENARIO PASSED (after 2 attempts)

  Scenario Outline: User asks to change the listener -- @1.3 set the listener requests      # features/change-listener.feature:12
    Given an english speaking user                                                          # features/steps/utterance_responses.py:120 0.000s
    When the user says "change the wake word engine to pocketsphinx"                        # features/steps/utterance_responses.py:125 0.000s
    Then "mycroft-configuration" should reply with "I've set the listener to pocket sphinx" # features/steps/utterance_responses.py:149
    Then "mycroft-configuration" should reply with "I've set the listener to pocket sphinx" # features/steps/utterance_responses.py:149 10.078s
      Assertion Failed: Mycroft responded with:
      Mycroft: listener.same.dialog(ConfigurationSkill)
      "The listener is already set to pocket sphinx."
      
      Captured stdout:
      Matching with the dialog file: set.listener.dialog
      
      Captured logging:
      INFO:msm.mycroft_skills_manager:Best match (1.0): mycroft-configuration by mycroftai

AUTO-RETRY SCENARIO (attempt 1)

  Scenario Outline: User asks to change the listener -- @1.3 set the listener requests      # features/change-listener.feature:12
    Given an english speaking user                                                          # features/steps/utterance_responses.py:120 0.000s
    When the user says "change the wake word engine to pocketsphinx"                        # features/steps/utterance_responses.py:125 0.000s
    Then "mycroft-configuration" should reply with "I've set the listener to pocket sphinx" # features/steps/utterance_responses.py:149
    Then "mycroft-configuration" should reply with "I've set the listener to pocket sphinx" # features/steps/utterance_responses.py:149 0.478s
AUTO-RETRY SCENARIO PASSED (after 2 attempts)

  Scenario Outline: User asks to change the listener -- @1.4 set the listener requests  # features/change-listener.feature:13
    Given an english speaking user                                                      # features/steps/utterance_responses.py:120 0.000s
    When the user says "make it the default listener"                                   # features/steps/utterance_responses.py:125 0.000s
    Then "mycroft-configuration" should reply with "I've set the listener to precise"   # features/steps/utterance_responses.py:149
    Then "mycroft-configuration" should reply with "I've set the listener to precise"   # features/steps/utterance_responses.py:149 10.068s
      Assertion Failed: Mycroft responded with:
      Mycroft: listener.same.dialog(ConfigurationSkill)
      "The listener is already set to precise."
      
      Captured stdout:
      Matching with the dialog file: set.listener.dialog
      
      Captured logging:
      INFO:msm.mycroft_skills_manager:Best match (1.0): mycroft-configuration by mycroftai

AUTO-RETRY SCENARIO (attempt 1)

  Scenario Outline: User asks to change the listener -- @1.4 set the listener requests  # features/change-listener.feature:13
    Given an english speaking user                                                      # features/steps/utterance_responses.py:120 0.000s
    When the user says "make it the default listener"                                   # features/steps/utterance_responses.py:125 0.000s
    Then "mycroft-configuration" should reply with "I've set the listener to precise"   # features/steps/utterance_responses.py:149
    Then "mycroft-configuration" should reply with "I've set the listener to precise"   # features/steps/utterance_responses.py:149 0.409s
AUTO-RETRY SCENARIO PASSED (after 2 attempts)
2020-04-23 09:33:39,388 | Voight Kampff | INFO | Result: passed (2.06s)

1 feature passed, 0 failed, 0 skipped
4 scenarios passed, 0 failed, 0 skipped
12 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m2.059s
Stopping all mycroft-core services
Stopping skills (37664)...failed to stop.
  Killing skills (37664)...killed.
Stopping audio (37667)...stopped.
Stopping speech (37670)...stopped.
Stopping enclosure (37673)...stopped.
Stopping messagebus.service (37661)...stopped.
```

**Comment by forslund** [comment]
Still haven't been able to reproduce the issue, can you check the skills.log if there's any missed intents or similar showing there?

**Comment by krisgesling** [comment]
Definitely not missing intents as it's responding with `listener.same.dialog` from the correct intent. 

I think we just have a race condition. Following the each successful utterance to change the listener, the following utterance is received < 1.1s later and it fails. Then the auto-retry pauses for around 9s before the next utterance is emited and it succeeds. 

The tests still pass due to the auto-retry so it could still be merged

**Comment by forslund** [comment]
I agree that it can be merged, will be interesting to see if this shows up on the jenkins job as well.

Though I'm not quite sure I follow where you think the race condition is, when we're clearing the message queue after the test?

**Pull request merged**
